name: SIH PS Tracker

on:
  schedule:
    - cron: "*/10 * * * *"   # ⏰ Runs every 10 minutes
  workflow_dispatch:         # Allows manual run from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run tracker
        run: python Count.py
